### ISSUE TITLE
Does xfuzz only support these three processor designs?

### ISSUE THREAD

**Issue by 90ICEDA** [OpenXiangShan/xfuzz#7]
Support for detection of other risc-v processors?

**Comment by poemonsense** [comment]
In short, xfuzz does not support any specific RISC-V processors. What it support is anything (not even a hardware) that implements the required interfaces listed in [harness.rs](https://github.com/OpenXiangShan/xfuzz/blob/main/src/harness.rs).

To explain more on this, xfuzz is a fuzzing framework for any design whose simulation framework (or anything) provides the required interfaces described in [this harness.rs Rust source file](https://github.com/OpenXiangShan/xfuzz/blob/main/src/harness.rs). You can even call xfuzz as a LibAFL wrapper with specific interfaces between the fuzzer and the design-under-test. Please refer to the section [Integrating Hardware Designs](https://github.com/OpenXiangShan/xfuzz?tab=readme-ov-file#integrating-hardware-designs) in the README of this repo for more detailed information.

The reason we are only providing thee examples is that, the only framework supporting these interfaces, DiffTest, provides offcial and public examples for only three processors.

That is to say, if you have any other processors connected to DiffTest, they are naturally supported by xfuzz.

That is also to say, if you have any other simulation framework or even any C++ design implementing the required interfaces, they will also supported by xfuzz.
